name: publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_GITHUB_PAT }}
      - name: store-core-version
        run: echo PACKAGE_VERSION=`cat package.json | jq -r '.version'` >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: grouparoo/redirector:latest, grouparoo/redirector:v${{ env.PACKAGE_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
